# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode8
language: objective-c
# before_install: cd Example && pod install && cd -
podfile: Example/Podfile

before_install:
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install --project-directory=Example

script:
  - set -o pipefail && xcodebuild -workspace Example/BSGUtilities.xcworkspace -scheme BSGUtilities -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test | xcpretty
  - set -o pipefail && xcodebuild -workspace Example/BSGUtilities.xcworkspace -scheme BSGUtilities -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' test | xcpretty
  - pod lib lint --allow-warnings
