# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
# before_install: cd Example && pod install && cd -
podfile: Example/Podfile

before_install:
  - make install
  - instruments -s devices

script:
  - make test-ci
  - make lint
