# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
# before_install: cd Example && pod install && cd -
podfile: Example/Podfile

before_install:
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install --project-directory=Example
  - instruments -s devices

script:
  - set -o pipefail && xcodebuild -workspace Example/BSGUtilities.xcworkspace -scheme BSGUtilities -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test | xcpretty
  - set -o pipefail && xcodebuild -workspace Example/BSGUtilities.xcworkspace -scheme BSGUtilities -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' test | xcpretty
  - set -o pipefail && xcodebuild -workspace Example/BSGUtilities.xcworkspace -scheme BSGUtilities -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' test | xcpretty
  - pod lib lint --allow-warnings
